### ISSUE TITLE
Async Write and concurrency

### ISSUE THREAD

**Issue by lionpeloux** [ygoe/AsyncTcpClient#3]
Hello,

Thank you for sharing this promising library. I have a question regarding async write. Indeed, you don't provide a similar mechanism as what you do for reading.

As I understand the logic of your code, you pull asynchronously (but sequentially) every bytes that are available from the stream.

Why don't you chose to not provide such a buffer for writing the packets sequentially ad then pushing asynchronously all the packets to the (write) stream ? What about concurrency of several tight-loop calls to WriteAsync ? 

Thanks,
Lionel

**Comment by ygoe** [comment]
I'm sorry I don't understand what you mean.

The [`Send` method](https://github.com/ygoe/AsyncTcpClient/blob/master/AsyncTcpClient/AsyncTcpClient.cs#L292) is async (although it should better be named `SendAsync` then). You don't need any kind of buffer there. You just put all you want to send into that method and it will be sent immediately. You can also send *when* you want to. There's no need for yourself to wait for yourself to send something, you just do it when you do it. Whereas you never know when you receive something, it can happen at any time, and then you never know what you receive, so you must be able to take and process it bit by bit, not all you get at once.

**Comment by lionpeloux** [comment]
Thank you for your answer.

Yes my question was a bit fussy. My intention is to have some sort of "safe" read-write with acknowledgement from the server so I need to queue my writings and wait until they are acknowledge by the server. And decide what to do if the acknowledgement failed.

Anyway, your code is a great source of inspiration, specially the way you deal with the buffer (tail / head indices).

**Comment by ygoe** [comment]
Receiving and sending work differently, from a global perspective. When you receive data, it is already delivered. So it it certain that the data has reached its destination. It's there and it's waiting for the application to take it. The application cannot control when exactly it receives data. The buffer only serves the purpose that the application does not have to take everything that happened to arrive in a moment, but it can take as much as it needs and leave the rest for later.

Sending is the other end of the pipe. The application decides what to send, and when. It has full control over that, as opposed to receiving. A queue is not required because data can be sent at any time. It doesn't have to wait to be sent. Also, when the application sends data, it is only starting its way through the network. At this point, the application cannot do anything more, but it is still uncertain whether the data will reach its destination. Only the receiver will know that.

If the receiver chooses to acknowledge the data reception back to the sender, then that's application logic. Not all systems do that on the application layer. (The network layers below, like TCP, IP and Ethernet may do it, but that's transparent to the application.) If you need a queue of sent data packets that remain tracked until they're acknowledged by the receiver, then that's application logic and out of the scope of this class.

The data structure used in the buffer is called a ring buffer. The writing end walks around the circle writing, while the reading end walks around the circle, in the same direction, taking away data. If all goes well, then no memory allocations are required to buffer data. Only if the buffer becomes too small, the circle needs to be expanded, that is, a new array is allocated.
